### ISSUE TITLE
Doesn't produce output

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/nidaba#5]
When I run this command:

    nidaba batch -b otsu -l tesseract -o tesseract:grc+eng,extended=True -p spell_check:polytonic_greek -- /cluster/tufts/perseus_ocr/nidaba/teubner/ammonius_1966/*.tif

It produces the filestore and it gets through the rgb-to-gray and the binarization steps, but then it seems to hang and does not produce any OCR output.  When I request the status, it says that it is pending.
I will send my celery log file by email since I don't know how to attach it to this issue.

**Comment by sonofmun** [comment]
OK, so now when I run

    nidaba batch -b otsu -l tesseract -o tesseract:grc+eng,extended=True -- /cluster/tufts/perseus_ocr/nidaba/teubner/ammonius_1966/*.tif

It produces files with the following naming scheme: 00000046_img.rgb_to_gray_binarize.otsu_segmentation.tesseract.xml

But, while these files have <zone> elements for the graphemes, there is no text either within these zone elements or the <g> elements under them.  And, after producing all these files, the job fails with the following error message:

```
(nidaba)[mmunso01@omega026 ~]$ nidaba status 2ac06b4f-ca84-4fa6-af16-a6c4a85e3a1e
FAILURE
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/bin/nidaba", line 11, in <module>
    sys.exit(main())
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/cli.py", line 304, in status
    ret = batch.get_errors()
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/nidaba.py", line 142, in get_errors
    if len(batch['errors']) > 0:
KeyError: 'errors'
```

**Comment by sonofmun** [comment]
Upgraded to Tesseract 3.05 and the latest version of nidaba (`pip install --upgrade nidaba`) and everything worked fine, even with spellchecking.
