### ISSUE TITLE
API on Homer fails with a Broken pipe

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/nidaba#9]
The three jobs I sent to Homer to do the LXX all seem to have failed with a Broken pipe error.  So, for instance, the following command

    nidaba status -h http://139.18.40.155:8000/api/v1 0e81b36d-b20e-4f7a-8612-f69355d45352 | head

returns

```
Status: failed

2943/4915 tasks completed. 0 running.

Output files:


Errors:

nidaba.ocr.kraken (a): 
Traceback (most recent call last):
  File "/home/mmunson/envs/nidaba/bin/nidaba", line 11, in <module>
    sys.exit(main())
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/nidaba/cli.py", line 410, in status
    task['errors'][-1]))
  File "/home/mmunson/envs/nidaba/local/lib/python2.7/site-packages/click/utils.py", line 315, in echo
    file.flush()
IOError: [Errno 32] Broken pipe
```

And the job does not appear to be running any more.  The job ids for these three jobs are:

0e81b36d-b20e-4f7a-8612-f69355d45352
a9dfce52-5589-45be-a910-924cd63632f2
a754df9b-8216-42a4-97a5-7fe84d9c5e68

**Comment by mittagessen** [comment]
Fixed in 0.9.5
